### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by Yordroid** [OpenBuilds/OpenBuilds-CONTROL#243]
Electron failed to install correctly, please delete node_modules/electron 
and try installing again
    at getElectronPath (F:\Project\openbuilds\node_modules\electron\index.js:17:11)
    at Object.<anonymous> (F:\Project\openbuilds\node_modules\electron\index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)  
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\Project\openbuilds\node_modules\electron\cli.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)

node version =18

**Comment by petervanderwalt** [comment]
You'll note we don't use NPM start:

``` "start": "echo \"Error: no start script specified\" && exit 0", ````

See https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/package.json#L37-L41
